{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "microbin.fullname" . }}
  labels:
    {{- include "microbin.labels" . | nindent 4 }}
rules:
  # CRUD microbinservices
  - verbs:
      - get
      - list
      - create
      - delete
      - update
      - watch
    apiGroups:
      - microbin.bananaops.io
    resources:
      - microbinservices
{{- end }}
