apiVersion: v1
kind: Service
metadata:
  name: {{ include "microbin.fullname" . }}
  labels:
    {{- include "microbin.labels" . | nindent 4 }}
    {{- if .Values.service.additionalLabels }}
    {{- toYaml .Values.service.additionalLabels | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: web
      protocol: TCP
      name: web
  selector:
    {{- include "microbin.selectorLabels" . | nindent 4 }}
